name: gotas_da_felicidade
description: Um app de mensagens motivacionais diárias

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  http: ^1.1.0
  url_launcher: ^6.1.11
  provider: ^6.1.1
  firebase_core: ^2.15.0
  firebase_auth: ^4.14.0
  google_sign_in: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/