name: gotas_da_felicidade
description: Aplicativo de mensagens motivacionais

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependências básicas
  http: ^1.1.0
  shared_preferences: ^2.2.2
  share_plus: ^7.2.2
  url_launcher: ^6.1.11
  flutter_dotenv: ^5.2.1

  # Notificações
  flutter_local_notifications: ^16.3.0

  # Firebase (opcional - comentado por enquanto)
  # firebase_core: ^2.32.0
  # firebase_auth: ^4.20.0
  # cloud_firestore: ^4.17.5
  # google_sign_in: ^6.3.0
  # flutter_facebook_auth: ^7.1.0
  # sign_in_with_apple: ^5.0.0

  # Localização
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - .env