name: gotas_da_felicidade
description: "Aplicativo multilingue de motivação diária com IA - Drops of Happiness"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_messaging: ^14.9.4

  # IA
  google_generative_ai: ^0.2.1
  http: ^1.1.0

  # Gerenciamento de Estado
  provider: ^6.1.1

  # Armazenamento Local
  shared_preferences: ^2.2.2

  # Internacionalização
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/