// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHrk-32VCTBNbqCGdabMWgFkl1rdICrPQ',
    appId: '1:604279967203:web:8137373cc9a5a67d6164d6',
    messagingSenderId: '604279967203',
    projectId: 'gotasdafelicidade-760fa',
    authDomain: 'gotasdafelicidade-760fa.firebaseapp.com',
    storageBucket: 'gotasdafelicidade-760fa.firebasestorage.app',
    measurementId: 'G-QWZFL4DB5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMR8UtO6oH4wdXxPAltV_o8gs2jb1rwqQ',
    appId: '1:604279967203:android:fce03ed44a41c5026164d6',
    messagingSenderId: '604279967203',
    projectId: 'gotasdafelicidade-760fa',
    storageBucket: 'gotasdafelicidade-760fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTGJ5_-JHW1SDMu_1-073YhojXFuSONNE',
    appId: '1:604279967203:ios:12591e7aa2e35b906164d6',
    messagingSenderId: '604279967203',
    projectId: 'gotasdafelicidade-760fa',
    storageBucket: 'gotasdafelicidade-760fa.firebasestorage.app',
    iosBundleId: 'com.example.gotasDaFelicidade',
  );
}
